-- =========================================================
-- 00_init.sql
-- Archivo maestro de inicialización
-- =========================================================

\ir 01_enums.sql
\ir 02_auth.sql
\ir 03_inventario.sql
\ir 04_operacion.sql
\ir 05_asignaciones.sql
\ir 06_grupos_y_mando.sql
\ir 06b_patch_flotilla.sql
\ir 07_chat.sql
\ir 08_mapa_base.sql
\ir 09_mapa_avanzado.sql
\ir 10_tracking.sql
\ir 11_novedades_y_avisos.sql
\ir 12_validaciones_generales.sql
\ir 13_triggers_operativos.sql
\ir 14_vistas.sql
\ir 15_seed.sql
\ir 16_patch_poi_color.sql
\ir 17_patch_poi_nombre_unico.sql
\ir 18_patch_poi_icono_mil.sql
\ir 19_patch_poi_sidc.sql
\ir 20_patch_dibujo_libre.sql
\ir 21_patch_operacion_evento.sql
\ir 22_patch_estado_operacion_creacion.sql
\ir 23_streaming.sql
\ir 24_signos_vitales.sql
\ir 25_dispositivos.sql
