-- =========================================================
-- 19_patch_poi_sidc.sql
-- CONSOLIDADO en 16_patch_poi_color.sql
-- Este archivo se mantiene por compatibilidad con entornos
-- que ya lo aplicaron. No ejecuta nada nuevo.
-- =========================================================
